# Generated by Django 2.0.2 on 2018-02-11 13:12

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('description', models.TextField(blank=True, verbose_name='Descrição simples')),
                ('about', models.TextField(blank=True, verbose_name='Sobre o curso')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Inícil')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/images', verbose_name='Imagens')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criando em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['name'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
